[package]
name = "hello-world"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "20.3.1"

[dev-dependencies]
soroban-sdk = { version = "20.3.1", features = ["testutils"] }

[workspace]
members = ["contracts/hello-world"]
